-- MySQL Script generated by MySQL Workbench
-- lø. 09. sep. 2017 kl. 00.13 +0200
-- Model: RescueMe    Version: 1.0

-- RescueMe MySQL Model

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rm_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `password` CHAR(128) NOT NULL DEFAULT '',
  `email` VARCHAR(255) NOT NULL,
  `mobile_country` CHAR(4) NOT NULL,
  `mobile` VARCHAR(25) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `state` ENUM('pending', 'active', 'disabled', 'deleted') NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_idx` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issues` (
  `issue_id` INT(11) NOT NULL AUTO_INCREMENT,
  `issue_type` ENUM('planned', 'incident') NOT NULL,
  `issue_state` ENUM('open', 'closed') NOT NULL DEFAULT 'open',
  `issue_summary` TINYTEXT NOT NULL,
  `issue_description` TEXT NOT NULL,
  `issue_cause` TEXT NULL DEFAULT NULL,
  `issue_actions` TEXT NULL DEFAULT NULL,
  `issue_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `issue_sent` TIMESTAMP NULL DEFAULT NULL,
  `issue_send_to` VARCHAR(40) NOT NULL DEFAULT 'active',
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`issue_id`),
  INDEX `fk_issues_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_issues_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alerts` (
  `alert_id` INT(11) NOT NULL AUTO_INCREMENT,
  `alert_type` ENUM('info', 'warning', 'error') NOT NULL DEFAULT 'info',
  `alert_subject` TINYTEXT NULL DEFAULT NULL,
  `alert_message` TEXT NOT NULL,
  `alert_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `alert_until` TIMESTAMP NULL DEFAULT NULL,
  `alert_closeable` TINYINT(1) NOT NULL DEFAULT '1',
  `user_id` INT(11) NOT NULL,
  `issue_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`alert_id`),
  INDEX `fk_alerts_issues_idx` (`issue_id` ASC),
  INDEX `fk_alerts_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_alerts_issues`
    FOREIGN KEY (`issue_id`)
    REFERENCES `issues` (`issue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alerts_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alerts_closed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alerts_closed` (
  `alert_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `alert_id`),
  INDEX `fk_alerts_closed_users_idx` (`user_id` ASC),
  INDEX `fk_alerts_closed_alerts_idx` (`alert_id` ASC),
  CONSTRAINT `fk_alerts_closed_alerts`
    FOREIGN KEY (`alert_id`)
    REFERENCES `alerts` (`alert_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alerts_closed_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `versions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `versions` (
  `version_id` INT(6) NOT NULL AUTO_INCREMENT,
  `version_name` VARCHAR(255) NOT NULL,
  `version_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`version_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groups` (
  `group_id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_name` TINYTEXT NOT NULL,
  `group_owner_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`group_id`),
  INDEX `fk_groups_users_idx` (`group_owner_user_id` ASC),
  CONSTRAINT `fk_groups_users`
    FOREIGN KEY (`group_owner_user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logs` (
  `log_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `level` VARCHAR(20) NOT NULL,
  `message` TEXT NOT NULL,
  `context` LONGTEXT NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `client_ip` VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
  PRIMARY KEY (`log_id`),
  INDEX `level_idx` (`level` ASC),
  INDEX `name_idx` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `members` (
  `member_id` INT(11) NOT NULL AUTO_INCREMENT,
  `member_group_id` INT(11) NOT NULL,
  `member_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `fk_members_groups_idx` (`member_group_id` ASC),
  INDEX `fk_members_users_idx` (`member_user_id` ASC),
  CONSTRAINT `fk_members_groups`
    FOREIGN KEY (`member_group_id`)
    REFERENCES `groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_users`
    FOREIGN KEY (`member_user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `traces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traces` (
  `trace_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `trace_type` ENUM('trace', 'test', 'exercise') NOT NULL,
  `trace_name` VARCHAR(255) NOT NULL,
  `trace_alert_country` CHAR(4) NOT NULL,
  `trace_alert_number` VARCHAR(25) NOT NULL,
  `trace_ref` VARCHAR(255) NULL DEFAULT NULL,
  `trace_opened` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `trace_closed` TIMESTAMP NULL DEFAULT NULL,
  `trace_comments` TEXT NOT NULL,
  PRIMARY KEY (`trace_id`),
  INDEX `fk_traces_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_traces_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mobiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobiles` (
  `trace_id` INT(11) NOT NULL,
  `mobile_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mobile_name` CHAR(255) NOT NULL,
  `mobile_country` CHAR(4) NOT NULL,
  `mobile_number` VARCHAR(25) NOT NULL,
  `mobile_locale` VARCHAR(10) NOT NULL,
  `mobile_hash` VARCHAR(45) NULL DEFAULT NULL,
  `sms_text` TEXT NULL DEFAULT NULL,
  `sms_sent` TIMESTAMP NULL DEFAULT NULL,
  `sms_delivered` TIMESTAMP NULL DEFAULT NULL,
  `sms_mb_sent` ENUM('false', 'true') NOT NULL DEFAULT 'false',
  `sms2_sent` ENUM('false', 'true') NOT NULL DEFAULT 'false',
  `mobile_alerted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mobile_responded` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`mobile_id`),
  INDEX `fk_mobiles_traces_idx` (`trace_id` ASC),
  CONSTRAINT `fk_mobiles_traces`
    FOREIGN KEY (`trace_id`)
    REFERENCES `traces` (`trace_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modules` (
  `module_id` INT(4) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL DEFAULT '0',
  `type` VARCHAR(50) NOT NULL,
  `impl` VARCHAR(50) NOT NULL,
  `config` TEXT NOT NULL,
  PRIMARY KEY (`module_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `user_id` INT(11) NOT NULL,
  `role_name` VARCHAR(100) NOT NULL,
  `role_id` INT(11) NOT NULL,
  INDEX `role_name_idx` (`role_name` ASC),
  INDEX `role_id_idx` (`role_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permissions` (
  `role_id` INT(11) NOT NULL DEFAULT '0',
  `user_id` INT(11) NOT NULL DEFAULT '0',
  `access` VARCHAR(100) NOT NULL,
  `resource` VARCHAR(100) NOT NULL,
  INDEX `fk_permissions_roles_idx` (`role_id` ASC),
  CONSTRAINT `fk_permissions_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `positions` (
  `mobile_id` INT(11) NOT NULL,
  `pos_id` INT(11) NOT NULL AUTO_INCREMENT,
  `lat` DOUBLE NOT NULL,
  `lon` DOUBLE NOT NULL,
  `acc` INT(5) NOT NULL,
  `alt` INT(4) NOT NULL,
  `timestamp_device` TIMESTAMP NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pos_id`),
  INDEX `fk_positions_missing_idx` (`mobile_id` ASC),
  CONSTRAINT `fk_positions_mobiles`
    FOREIGN KEY (`mobile_id`)
    REFERENCES `mobiles` (`mobile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `properties` (
  `property_id` INT(4) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(50) NOT NULL,
  `value` TEXT NOT NULL,
  PRIMARY KEY (`property_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `templates` (
  `template_id` INT(11) NOT NULL AUTO_INCREMENT,
  `template_type` ENUM('message') NOT NULL DEFAULT 'message',
  `template_name` VARCHAR(50) NOT NULL,
  `template_locale` VARCHAR(10) NOT NULL,
  `template_content` TEXT NOT NULL,
  PRIMARY KEY (`template_id`),
  INDEX `template_name_idx` (`template_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messages` (
  `mobile_id` INT(11) NOT NULL,
  `message_id` INT(11) NOT NULL AUTO_INCREMENT,
  `message_type` ENUM('sms') NOT NULL,
  `message_locale` VARCHAR(10) NOT NULL,
  `message_text` TEXT NULL DEFAULT NULL,
  `message_provider` VARCHAR(255) NULL DEFAULT NULL,
  `message_provider_ref` VARCHAR(255) NULL DEFAULT NULL,
  `message_provider_status` VARCHAR(255) NULL DEFAULT NULL,
  `message_provider_error` BLOB NULL,
  `message_sent` TIMESTAMP NULL DEFAULT NULL,
  `message_delivered` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `fk_messages_mobiles_idx` (`mobile_id` ASC),
  CONSTRAINT `fk_messages_mobiles`
    FOREIGN KEY (`mobile_id`)
    REFERENCES `mobiles` (`mobile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `requests` (
  `request_id` INT(11) NOT NULL AUTO_INCREMENT,
  `request_ua` TEXT NOT NULL,
  `request_client_ip` VARCHAR(40) NULL,
  `request_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `request_type` ENUM('response', 'position') NOT NULL,
  `foreign_id` INT(11) NOT NULL,
  `mobile_id` INT(11) NOT NULL,
  PRIMARY KEY (`request_id`),
  INDEX `fk_requests_mobiles_idx` (`mobile_id` ASC),
  CONSTRAINT `fk_requests_mobiles`
    FOREIGN KEY (`mobile_id`)
    REFERENCES `mobiles` (`mobile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devices` (
  `device_id` INT NOT NULL,
  `device_type` VARCHAR(45) NULL,
  `device_os_name` VARCHAR(45) NULL,
  `device_os_version` VARCHAR(45) NULL,
  `device_browser_name` VARCHAR(45) NULL,
  `device_browser_version` VARCHAR(45) NULL,
  `device_is_phone` ENUM('true', 'false') NULL,
  `device_is_smartphone` ENUM('true', 'false') NULL,
  `device_supports_xhr2` ENUM('true', 'false') NULL,
  `device_supports_geolocation` ENUM('true', 'false') NULL,
  `device_lookup_provider` VARCHAR(45) NULL,
  `device_lookup_provider_ref` VARCHAR(45) NULL,
  `request_id` INT(11) NULL,
  PRIMARY KEY (`device_id`),
  INDEX `fk_devices_requests_idx` (`request_id` ASC),
  CONSTRAINT `fk_devices_requests`
    FOREIGN KEY (`request_id`)
    REFERENCES `requests` (`request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
