<?php

    /**
	 * locales
	 * 
	 * @copyright Copyright 2013 {@link http://www.onevoice.no One Voice AS} 
	 *
     * @since 25. July 2013, v. 8.00
	 * 
	 * @author Kenneth Gulbrandsøy <kenneth@onevoice.no>
	 */

$locales = array ( 
    'AF' => array ( 'country' => 'Afghanistan', 'dial_code' => '93', 'language' => array ( 'Dari' => 'prs_AF', 'Pashto' => 'ps_AF' )),
    'AL' => array ( 'country' => 'Albania', 'dial_code' => '355', 'language' => array ( 'Albanian' => 'sq_AL' )),
    'DZ' => array ( 'country' => 'Algeria', 'dial_code' => '213', 'language' => array ( 'Arabic' => 'ar_DZ', 'Tamazight (Latin)' => 'tzm_DZ' )),
    'AR' => array ( 'country' => 'Argentina', 'dial_code' => '54', 'language' => array ( 'Spanish' => 'es_AR' )),
    'AM' => array ( 'country' => 'Armenia', 'dial_code' => '374', 'language' => array ( 'Armenian' => 'hy_AM' )),
    'AU' => array ( 'country' => 'Australia', 'dial_code' => '61', 'language' => array ( 'English' => 'en_AU' )),
    'AT' => array ( 'country' => 'Austria', 'dial_code' => '43', 'language' => array ( 'German' => 'de_AT' )),
    'AZ' => array ( 'country' => 'Azerbaijan', 'dial_code' => '994', 'language' => array ( 'Azeri (Cyrillic)' => 'az_AZ', 'Azeri (Latin)' => 'az_AZ' )),
    'BH' => array ( 'country' => 'Bahrain', 'dial_code' => '973', 'language' => array ( 'Arabic' => 'ar_BH' )),
    'BD' => array ( 'country' => 'Bangladesh', 'dial_code' => '880', 'language' => array ( 'Bengali' => 'bn_BD' )),
    'BY' => array ( 'country' => 'Belarus', 'dial_code' => '375', 'language' => array ( 'Belarusian' => 'be_BY' )),
    'BE' => array ( 'country' => 'Belgium', 'dial_code' => '32', 'language' => array ( 'Dutch' => 'nl_BE', 'French' => 'fr_BE' )),
    'BZ' => array ( 'country' => 'Belize', 'dial_code' => '501', 'language' => array ( 'English' => 'en_BZ' )),
    'VE' => array ( 'country' => 'Bolivarian Republic of Venezuela', 'dial_code' => '58', 'language' => array ( 'Spanish' => 'es_VE' )),
    'BO' => array ( 'country' => 'Bolivia', 'dial_code' => '591', 'language' => array ( 'Quechua' => 'quz_BO', 'Spanish' => 'es_BO' )),
    'BA' => array ( 'country' => 'Bosnia and Herzegovina', 'dial_code' => '387', 'language' => array ( 'Bosnian (Cyrillic)' => 'bs_BA', 'Bosnian (Latin)' => 'bs_BA', 'Croatian' => 'hr_BA', 'Serbian (Cyrillic)' => 'sr_BA', 'Serbian (Latin)' => 'sr_BA' )),
    'BR' => array ( 'country' => 'Brazil', 'dial_code' => '55', 'language' => array ( 'Portuguese' => 'pt_BR' )),
    'BN' => array ( 'country' => 'Brunei Darussalam', 'dial_code' => '673', 'language' => array ( 'Malay' => 'ms_BN' )),
    'BG' => array ( 'country' => 'Bulgaria', 'dial_code' => '359', 'language' => array ( 'Bulgarian' => 'bg_BG' )),
    'KH' => array ( 'country' => 'Cambodia', 'dial_code' => '855', 'language' => array ( 'Khmer' => 'km_KH' )),
    'CA' => array ( 'country' => 'Canada', 'dial_code' => '1', 'language' => array ( 'English' => 'en_CA', 'French' => 'fr_CA', 'Inuktitut (Latin)' => 'iu_CA', 'Inuktitut (Syllabics)' => 'iu_CA', 'Mohawk' => 'moh_CA' )),
    'CL' => array ( 'country' => 'Chile', 'dial_code' => '56', 'language' => array ( 'Mapudungun' => 'arn_CL', 'Spanish' => 'es_CL' )),
    'CO' => array ( 'country' => 'Colombia', 'dial_code' => '57', 'language' => array ( 'Spanish' => 'es_CO' )),
    'CR' => array ( 'country' => 'Costa Rica', 'dial_code' => '506', 'language' => array ( 'Spanish' => 'es_CR' )),
    'HR' => array ( 'country' => 'Croatia', 'dial_code' => '385', 'language' => array ( 'Croatian' => 'hr_HR' )),
    'CZ' => array ( 'country' => 'Czech Republic', 'dial_code' => '420', 'language' => array ( 'Czech' => 'cs_CZ' )),
    'DK' => array ( 'country' => 'Denmark', 'dial_code' => '45', 'language' => array ( 'Danish' => 'da_DK' )),
    'DO' => array ( 'country' => 'Dominican Republic', 'dial_code' => '1809', 'language' => array ( 'Spanish' => 'es_DO' )),
    'EC' => array ( 'country' => 'Ecuador', 'dial_code' => '593', 'language' => array ( 'Quechua' => 'quz_EC', 'Spanish' => 'es_EC' )),
    'EG' => array ( 'country' => 'Egypt', 'dial_code' => '20', 'language' => array ( 'Arabic' => 'ar_EG' )),
    'SV' => array ( 'country' => 'El Salvador', 'dial_code' => '503', 'language' => array ( 'Spanish' => 'es_SV' )),
    'EE' => array ( 'country' => 'Estonia', 'dial_code' => '372', 'language' => array ( 'Estonian' => 'et_EE' )),
    'ET' => array ( 'country' => 'Ethiopia', 'dial_code' => '251', 'language' => array ( 'Amharic' => 'am_ET' )),
    'FO' => array ( 'country' => 'Faroe Islands', 'dial_code' => '298', 'language' => array ( 'Faroese' => 'fo_FO' )),
    'FI' => array ( 'country' => 'Finland', 'dial_code' => '358', 'language' => array ( 'Finnish' => 'fi_FI', 'Sami (Inari)' => 'smn_FI', 'Sami (Northern)' => 'se_FI', 'Sami (Skolt)' => 'sms_FI', 'Swedish' => 'sv_FI' )),
    'FR' => array ( 'country' => 'France', 'dial_code' => '33', 'language' => array ( 'Alsatian' => 'gsw_FR', 'Breton' => 'br_FR', 'Corsican' => 'co_FR', 'French' => 'fr_FR', 'Occitan' => 'oc_FR' )),
    'GE' => array ( 'country' => 'Georgia', 'dial_code' => '995', 'language' => array ( 'Georgian' => 'ka_GE' )),
    'DE' => array ( 'country' => 'Germany', 'dial_code' => '49', 'language' => array ( 'German' => 'de_DE', 'Lower Sorbian' => 'dsb_DE', 'Upper Sorbian' => 'hsb_DE' )),
    'GR' => array ( 'country' => 'Greece', 'dial_code' => '30', 'language' => array ( 'Greek' => 'el_GR' )),
    'GL' => array ( 'country' => 'Greenland', 'dial_code' => '299', 'language' => array ( 'Greenlandic' => 'kl_GL' )),
    'GT' => array ( 'country' => 'Guatemala', 'dial_code' => '502', 'language' => array ( 'K\'iche' => 'qut_GT', 'Spanish' => 'es_GT' )),
    'HN' => array ( 'country' => 'Honduras', 'dial_code' => '504', 'language' => array ( 'Spanish' => 'es_HN' )),
    'HK' => array ( 'country' => 'Hong Kong S.A.R.', 'dial_code' => '852', 'language' => array ( 'Chinese (Traditional) Legacy' => 'zh_HK' )),
    'HU' => array ( 'country' => 'Hungary', 'dial_code' => '36', 'language' => array ( 'Hungarian' => 'hu_HU' )),
    'IS' => array ( 'country' => 'Iceland', 'dial_code' => '354', 'language' => array ( 'Icelandic' => 'is_IS' )),
    'IN' => array ( 'country' => 'India', 'dial_code' => '91', 'language' => array ( 'Assamese' => 'as_IN', 'Bengali' => 'bn_IN', 'English' => 'en_IN', 'Gujarati' => 'gu_IN', 'Hindi' => 'hi_IN', 'Kannada' => 'kn_IN', 'Konkani' => 'kok_IN', 'Malayalam' => 'ml_IN', 'Marathi' => 'mr_IN', 'Oriya' => 'or_IN', 'Punjabi' => 'pa_IN', 'Sanskrit' => 'sa_IN', 'Tamil' => 'ta_IN', 'Telugu' => 'te_IN' )),
    'ID' => array ( 'country' => 'Indonesia', 'dial_code' => '62', 'language' => array ( 'Indonesian' => 'id_ID' )),
    'IR' => array ( 'country' => 'Iran', 'dial_code' => '98', 'language' => array ( 'Persian' => 'fa_IR' )),
    'IQ' => array ( 'country' => 'Iraq', 'dial_code' => '964', 'language' => array ( 'Arabic' => 'ar_IQ' )),
    'IE' => array ( 'country' => 'Ireland', 'dial_code' => '353', 'language' => array ( 'English' => 'en_IE', 'Irish' => 'ga_IE' )),
    'PK' => array ( 'country' => 'Islamic Republic of Pakistan', 'dial_code' => '92', 'language' => array ( 'Urdu' => 'ur_PK' )),
    'IL' => array ( 'country' => 'Israel', 'dial_code' => '972', 'language' => array ( 'Hebrew' => 'he_IL' )),
    'IT' => array ( 'country' => 'Italy', 'dial_code' => '39', 'language' => array ( 'Italian' => 'it_IT' )),
    'JM' => array ( 'country' => 'Jamaica', 'dial_code' => '1876', 'language' => array ( 'English' => 'en_JM' )),
    'JP' => array ( 'country' => 'Japan', 'dial_code' => '81', 'language' => array ( 'Japanese' => 'ja_JP' )),
    'JO' => array ( 'country' => 'Jordan', 'dial_code' => '962', 'language' => array ( 'Arabic' => 'ar_JO' )),
    'KZ' => array ( 'country' => 'Kazakhstan', 'dial_code' => '7', 'language' => array ( 'Kazakh' => 'kk_KZ' )),
    'KE' => array ( 'country' => 'Kenya', 'dial_code' => '254', 'language' => array ( 'Kiswahili' => 'sw_KE' )),
    'KR' => array ( 'country' => 'Korea', 'dial_code' => '82', 'language' => array ( 'Korean' => 'ko_KR' )),
    'KW' => array ( 'country' => 'Kuwait', 'dial_code' => '965', 'language' => array ( 'Arabic' => 'ar_KW' )),
    'KG' => array ( 'country' => 'Kyrgyzstan', 'dial_code' => '996', 'language' => array ( 'Kyrgyz' => 'ky_KG' )),
    'LA' => array ( 'country' => 'Lao P.D.R.', 'dial_code' => '856', 'language' => array ( 'Lao' => 'lo_LA' )),
    'LV' => array ( 'country' => 'Latvia', 'dial_code' => '371', 'language' => array ( 'Latvian' => 'lv_LV' )),
    'LB' => array ( 'country' => 'Lebanon', 'dial_code' => '961', 'language' => array ( 'Arabic' => 'ar_LB' )),
    'LY' => array ( 'country' => 'Libya', 'dial_code' => '218', 'language' => array ( 'Arabic' => 'ar_LY' )),
    'LI' => array ( 'country' => 'Liechtenstein', 'dial_code' => '423', 'language' => array ( 'German' => 'de_LI' )),
    'LT' => array ( 'country' => 'Lithuania', 'dial_code' => '370', 'language' => array ( 'Lithuanian' => 'lt_LT' )),
    'LU' => array ( 'country' => 'Luxembourg', 'dial_code' => '352', 'language' => array ( 'French' => 'fr_LU', 'German' => 'de_LU', 'Luxembourgish' => 'lb_LU' )),
    'MO' => array ( 'country' => 'Macao S.A.R.', 'dial_code' => '853', 'language' => array ( 'Chinese (Traditional) Legacy' => 'zh_MO' )),
    'MK' => array ( 'country' => 'Macedonia (FYROM)', 'dial_code' => '389', 'language' => array ( 'Macedonian (FYROM)' => 'mk_MK' )),
    'MY' => array ( 'country' => 'Malaysia', 'dial_code' => '60', 'language' => array ( 'English' => 'en_MY', 'Malay' => 'ms_MY' )),
    'MV' => array ( 'country' => 'Maldives', 'dial_code' => '960', 'language' => array ( 'Divehi' => 'dv_MV' )),
    'MT' => array ( 'country' => 'Malta', 'dial_code' => '356', 'language' => array ( 'Maltese' => 'mt_MT' )),
    'MX' => array ( 'country' => 'Mexico', 'dial_code' => '52', 'language' => array ( 'Spanish' => 'es_MX' )),
    'MN' => array ( 'country' => 'Mongolia', 'dial_code' => '976', 'language' => array ( 'Mongolian (Cyrillic)' => 'mn_MN' )),
    'ME' => array ( 'country' => 'Montenegro', 'dial_code' => '382', 'language' => array ( 'Serbian (Cyrillic)' => 'sr_ME', 'Serbian (Latin)' => 'sr_ME' )),
    'MA' => array ( 'country' => 'Morocco', 'dial_code' => '212', 'language' => array ( 'Arabic' => 'ar_MA' )),
    'NP' => array ( 'country' => 'Nepal', 'dial_code' => '977', 'language' => array ( 'Nepali' => 'ne_NP' )),
    'NL' => array ( 'country' => 'Netherlands', 'dial_code' => '31', 'language' => array ( 'Dutch' => 'nl_NL', 'Frisian' => 'fy_NL' )),
    'NZ' => array ( 'country' => 'New Zealand', 'dial_code' => '64', 'language' => array ( 'English' => 'en_NZ', 'Maori' => 'mi_NZ' )),
    'NI' => array ( 'country' => 'Nicaragua', 'dial_code' => '505', 'language' => array ( 'Spanish' => 'es_NI' )),
    'NG' => array ( 'country' => 'Nigeria', 'dial_code' => '234', 'language' => array ( 'Hausa (Latin)' => 'ha_NG', 'Igbo' => 'ig_NG', 'Yoruba' => 'yo_NG' )),
    'NO' => array ( 'country' => 'Norway', 'dial_code' => '47', 'language' => array ( 'Norwegian (Bokmal)' => 'nb_NO', 'Norwegian (Nynorsk)' => 'nn_NO', 'Sami (Lule)' => 'smj_NO', 'Sami (Northern)' => 'se_NO', 'Sami (Southern)' => 'sma_NO' )),
    'OM' => array ( 'country' => 'Oman', 'dial_code' => '968', 'language' => array ( 'Arabic' => 'ar_OM' )),
    'PA' => array ( 'country' => 'Panama', 'dial_code' => '507', 'language' => array ( 'Spanish' => 'es_PA' )),
    'PY' => array ( 'country' => 'Paraguay', 'dial_code' => '595', 'language' => array ( 'Spanish' => 'es_PY' )),
    'CN' => array ( 'country' => 'China', 'dial_code' => '86', 'language' => array ( 'Chinese (Simplified) Legacy' => 'zh_CN', 'Mongolian (Traditional Mongolian)' => 'mn_CN', 'Tibetan' => 'bo_CN', 'Uyghur' => 'ug_CN', 'Yi' => 'ii_CN' )),
    'PE' => array ( 'country' => 'Peru', 'dial_code' => '51', 'language' => array ( 'Quechua' => 'quz_PE', 'Spanish' => 'es_PE' )),
    'PH' => array ( 'country' => 'Philippines', 'dial_code' => '63', 'language' => array ( 'Filipino' => 'fil_PH', 'English' => 'en_PH' )),
    'PL' => array ( 'country' => 'Poland', 'dial_code' => '48', 'language' => array ( 'Polish' => 'pl_PL' )),
    'PT' => array ( 'country' => 'Portugal', 'dial_code' => '351', 'language' => array ( 'Portuguese' => 'pt_PT' )),
    'MC' => array ( 'country' => 'Principality of Monaco', 'dial_code' => '377', 'language' => array ( 'French' => 'fr_MC' )),
    'PR' => array ( 'country' => 'Puerto Rico', 'dial_code' => '1', 'language' => array ( 'Spanish' => 'es_PR' )),
    'QA' => array ( 'country' => 'Qatar', 'dial_code' => '974', 'language' => array ( 'Arabic' => 'ar_QA' )),
    'RO' => array ( 'country' => 'Romania', 'dial_code' => '40', 'language' => array ( 'Romanian' => 'ro_RO' )),
    'RU' => array ( 'country' => 'Russia', 'dial_code' => '7', 'language' => array ( 'Bashkir' => 'ba_RU', 'Russian' => 'ru_RU', 'Tatar' => 'tt_RU', 'Yakut' => 'sah_RU' )),
    'RW' => array ( 'country' => 'Rwanda', 'dial_code' => '250', 'language' => array ( 'Kinyarwanda' => 'rw_RW' )),
    'SA' => array ( 'country' => 'Saudi Arabia', 'dial_code' => '966', 'language' => array ( 'Arabic' => 'ar_SA' )),
    'SN' => array ( 'country' => 'Senegal', 'dial_code' => '221', 'language' => array ( 'Wolof' => 'wo_SN' )),
    'RS' => array ( 'country' => 'Serbia', 'dial_code' => '381', 'language' => array ( 'Serbian (Cyrillic)' => 'sr_RS', 'Serbian (Latin)' => 'sr_RS' )),
    'CS' => array ( 'country' => 'Serbia and Montenegro (Former)', 'dial_code' => '', 'language' => array ( 'Serbian (Latin)' => 'sr_CS' )),
    'SG' => array ( 'country' => 'Singapore', 'dial_code' => '65', 'language' => array ( 'Chinese (Simplified) Legacy' => 'zh_SG', 'English' => 'en_SG' )),
    'SK' => array ( 'country' => 'Slovakia', 'dial_code' => '421', 'language' => array ( 'Slovak' => 'sk_SK' )),
    'SI' => array ( 'country' => 'Slovenia', 'dial_code' => '386', 'language' => array ( 'Slovenian' => 'sl_SI' )),
    'ZA' => array ( 'country' => 'South Africa', 'dial_code' => '27', 'language' => array ( 'Afrikaans' => 'af_ZA', 'English' => 'en_ZA', 'isiXhosa' => 'xh_ZA', 'isiZulu' => 'zu_ZA', 'Sesotho sa Leboa' => 'nso_ZA', 'Setswana' => 'tn_ZA' )),
    'ES' => array ( 'country' => 'Spain', 'dial_code' => '34', 'language' => array ( 'Basque' => 'eu_ES', 'Catalan' => 'ca_ES', 'Galician' => 'gl_ES', 'Spanish' => 'es_ES' )),
    'LK' => array ( 'country' => 'Sri Lanka', 'dial_code' => '94', 'language' => array ( 'Sinhala' => 'si_LK' )),
    'SE' => array ( 'country' => 'Sweden', 'dial_code' => '46', 'language' => array ( 'Sami (Lule)' => 'smj_SE', 'Sami (Northern)' => 'se_SE', 'Sami (Southern)' => 'sma_SE', 'Swedish' => 'sv_SE' )),
    'CH' => array ( 'country' => 'Switzerland', 'dial_code' => '41', 'language' => array ( 'French' => 'fr_CH', 'German' => 'de_CH', 'Italian' => 'it_CH', 'Romansh' => 'rm_CH' )),
    'SY' => array ( 'country' => 'Syria', 'dial_code' => '963', 'language' => array ( 'Arabic' => 'ar_SY', 'Syriac' => 'syr_SY' )),
    'TW' => array ( 'country' => 'Taiwan', 'dial_code' => '886', 'language' => array ( 'Chinese (Traditional) Legacy' => 'zh_TW' )),
    'TJ' => array ( 'country' => 'Tajikistan', 'dial_code' => '992', 'language' => array ( 'Tajik (Cyrillic)' => 'tg_TJ' )),
    'TH' => array ( 'country' => 'Thailand', 'dial_code' => '66', 'language' => array ( 'Thai' => 'th_TH' )),
    'TT' => array ( 'country' => 'Trinidad and Tobago', 'dial_code' => '1868', 'language' => array ( 'English' => 'en_TT' )),
    'TN' => array ( 'country' => 'Tunisia', 'dial_code' => '216', 'language' => array ( 'Arabic' => 'ar_TN' )),
    'TR' => array ( 'country' => 'Turkey', 'dial_code' => '90', 'language' => array ( 'Turkish' => 'tr_TR' )),
    'TM' => array ( 'country' => 'Turkmenistan', 'dial_code' => '993', 'language' => array ( 'Turkmen' => 'tk_TM' )),
    'AE' => array ( 'country' => 'United Arab Emirates', 'dial_code' => '971', 'language' => array ( 'Arabic' => 'ar_AE' )),
    'UA' => array ( 'country' => 'Ukraine', 'dial_code' => '380', 'language' => array ( 'Ukrainian' => 'uk_UA' )),
    'GB' => array ( 'country' => 'United Kingdom', 'dial_code' => '44', 'language' => array ( 'English' => 'en_GB', 'Scottish Gaelic' => 'gd_GB', 'Welsh' => 'cy_GB' )),
    'US' => array ( 'country' => 'United States', 'dial_code' => '1', 'language' => array ( 'English' => 'en_US', 'Spanish' => 'es_US' )),
    'UY' => array ( 'country' => 'Uruguay', 'dial_code' => '598', 'language' => array ( 'Spanish' => 'es_UY' )),
    'UZ' => array ( 'country' => 'Uzbekistan', 'dial_code' => '998', 'language' => array ( 'Uzbek (Cyrillic)' => 'uz_UZ', 'Uzbek (Latin)' => 'uz_UZ' )),
    'VN' => array ( 'country' => 'Vietnam', 'dial_code' => '84', 'language' => array ( 'Vietnamese' => 'vi_VN' )),
    'YE' => array ( 'country' => 'Yemen', 'dial_code' => '967', 'language' => array ( 'Arabic' => 'ar_YE' )),
    'ZW' => array ( 'country' => 'Zimbabwe', 'dial_code' => '263', 'language' => array ( 'English' => 'en_ZW' ))
 );

return $locales;